name: audio-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - numpy
  - scipy
  - matplotlib
  - pandas
  - ffmpeg           # conda package
  - pip
  - pip:
    - librosa
    - pydub
