name: audio-tutorial
channels:
  - conda-forge
dependencies:
  # minimal Conda-level packages
  - python=3.10
  - pip
  - ffmpeg       # from conda-forge

  # now pip-install everything else
  - pip:
      - jupyterlab
      - ipywidgets
      - numpy
      - scipy
      - matplotlib
      - pandas
      - librosa
      - pydub
